ALTER TABLE "Property"
ADD COLUMN IF NOT EXISTS "searchImpressions" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "Property"
ADD COLUMN IF NOT EXISTS "profileViews" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "Property"
ADD COLUMN IF NOT EXISTS "favoritesCount" INTEGER NOT NULL DEFAULT 0;
