INSERT INTO "RoomFeature" ("id", "name", "category", "isActive", "updatedAt") VALUES
  ('shower', 'Душ', 'Ванная/санузел', true, NOW()),
  ('bath', 'Ванна', 'Ванная/санузел', true, NOW()),
  ('shower_cabin', 'Душевая кабина', 'Ванная/санузел', true, NOW()),
  ('toilet', 'Унитаз', 'Ванная/санузел', true, NOW()),
  ('urinal', 'Писсуар', 'Ванная/санузел', true, NOW()),
  ('bidet', 'Биде', 'Ванная/санузел', true, NOW()),
  ('hygienic_shower', 'Гигиенический душ', 'Ванная/санузел', true, NOW()),
  ('toiletries', 'Туалетно-косметические принадлежности', 'Ванная/санузел', true, NOW()),
  ('hair_dryer', 'Фен', 'Ванная/санузел', true, NOW()),
  ('bathrobe', 'Халат', 'Одежда/текстиль', true, NOW()),
  ('slippers', 'Тапочки', 'Одежда/текстиль', true, NOW()),
  ('air_conditioner', 'Кондиционер', 'Температурный режим', true, NOW()),
  ('fan', 'Вентилятор', 'Температурный режим', true, NOW()),
  ('heating', 'Отопление', 'Температурный режим', true, NOW()),
  ('heater', 'Обогреватель', 'Температурный режим', true, NOW()),
  ('fireplace', 'Камин', 'Температурный режим', true, NOW()),
  ('electric_blanket', 'Одеяло с электроподогревом', 'Температурный режим', true, NOW()),
  ('heated_floor', 'Теплый пол', 'Температурный режим', true, NOW()),
  ('private_kitchen', 'Кухня', 'Кухня/питание', true, NOW()),
  ('kitchenette', 'Мини-кухня', 'Кухня/питание', true, NOW()),
  ('refrigerator', 'Холодильник', 'Кухня/питание', true, NOW()),
  ('stove', 'Плита', 'Кухня/питание', true, NOW()),
  ('oven', 'Духовка', 'Кухня/питание', true, NOW()),
  ('microwave', 'Микроволновая печь', 'Кухня/питание', true, NOW()),
  ('kettle', 'Чайник', 'Кухня/питание', true, NOW()),
  ('coffee_machine', 'Кофемашина', 'Кухня/питание', true, NOW()),
  ('cookware', 'Кухонные принадлежности / посуда / приборы', 'Кухня/питание', true, NOW()),
  ('mini_bar', 'Мини-бар', 'Кухня/питание', true, NOW()),
  ('water_tea_coffee', 'Вода / чай / кофе', 'Кухня/питание', true, NOW()),
  ('washing_machine', 'Стиральная машина', 'Уход за одеждой', true, NOW()),
  ('dryer', 'Сушилка', 'Уход за одеждой', true, NOW()),
  ('dryer_machine', 'Сушильная машина', 'Уход за одеждой', true, NOW()),
  ('clothes_dryer', 'Сушилка для белья', 'Уход за одеждой', true, NOW()),
  ('iron', 'Утюг', 'Уход за одеждой', true, NOW()),
  ('ironing_board', 'Гладильная доска', 'Уход за одеждой', true, NOW()),
  ('panoramic_windows', 'Панорамные окна', 'Вид из окна', true, NOW()),
  ('no_window', 'Без окна', 'Вид из окна', true, NOW()),
  ('balcony', 'Балкон', 'Вид из окна', true, NOW()),
  ('view_city', 'Вид на город', 'Вид из окна', true, NOW()),
  ('view_river', 'Вид на реку', 'Вид из окна', true, NOW()),
  ('view_lake', 'Вид на озеро', 'Вид из окна', true, NOW()),
  ('view_sea', 'Вид на море', 'Вид из окна', true, NOW()),
  ('view_ocean', 'Вид на океан', 'Вид из окна', true, NOW()),
  ('view_embankment', 'Вид на набережную', 'Вид из окна', true, NOW()),
  ('view_forest', 'Вид на лес', 'Вид из окна', true, NOW()),
  ('view_mountain', 'Вид на горы', 'Вид из окна', true, NOW()),
  ('view_stadium', 'Вид на стадион', 'Вид из окна', true, NOW()),
  ('view_landmark', 'Вид на достопримечательность', 'Вид из окна', true, NOW()),
  ('view_courtyard', 'Вид во двор', 'Вид из окна', true, NOW()),
  ('partial_sea_view', 'Частичный вид на море', 'Вид из окна', true, NOW()),
  ('wifi', 'Интернет', 'Для работы', true, NOW()),
  ('desk', 'Рабочий стол', 'Для работы', true, NOW()),
  ('sockets_near_desk', 'Розетки около стола', 'Для работы', true, NOW()),
  ('adapter', 'Переходник', 'Для работы', true, NOW()),
  ('usb_port', 'USB-порт', 'Для работы', true, NOW()),
  ('work_chair', 'Рабочее кресло', 'Для работы', true, NOW()),
  ('desk_lamp', 'Настольная лампа', 'Для работы', true, NOW()),
  ('monitor', 'Монитор', 'Для работы', true, NOW()),
  ('tv', 'Телевизор', 'Развлечения', true, NOW()),
  ('online_cinema', 'Онлайн-кинотеатр', 'Развлечения', true, NOW()),
  ('yandex_station', 'Яндекс Станция', 'Развлечения', true, NOW()),
  ('kids_slippers', 'Детские тапочки', 'Отдых с детьми', true, NOW()),
  ('kids_bathrobe', 'Детский халат', 'Отдых с детьми', true, NOW()),
  ('kids_toiletries', 'Детские туалетно-косметические принадлежности', 'Отдых с детьми', true, NOW()),
  ('playpen', 'Детский манеж', 'Отдых с детьми', true, NOW()),
  ('feeding_chair', 'Стульчик для кормления', 'Отдых с детьми', true, NOW()),
  ('changing_table', 'Пеленальный стол', 'Отдых с детьми', true, NOW()),
  ('baby_bath', 'Детская ванночка', 'Отдых с детьми', true, NOW()),
  ('baby_monitor', 'Радионяня', 'Отдых с детьми', true, NOW()),
  ('pet_food_bowl', 'Миска для корма', 'Отдых с животными', true, NOW()),
  ('pet_water_bowl', 'Миска для воды', 'Отдых с животными', true, NOW()),
  ('pet_toiletries', 'Туалетно-косметические принадлежности для животных', 'Отдых с животными', true, NOW()),
  ('pet_bed', 'Лежак', 'Отдых с животными', true, NOW()),
  ('pet_towels', 'Полотенца для купания животных', 'Отдых с животными', true, NOW()),
  ('pet_pads', 'Пеленки', 'Отдых с животными', true, NOW()),
  ('pet_cleanup_bags', 'Пакеты для уборки', 'Отдых с животными', true, NOW()),
  ('pet_food', 'Корм для животных', 'Отдых с животными', true, NOW()),
  ('bedside_handrails', 'Прикроватные поручни', 'Безбарьерная среда', true, NOW()),
  ('bath_handrails', 'Ванна с поручнями', 'Безбарьерная среда', true, NOW()),
  ('toilet_handrails', 'Унитаз с поручнями', 'Безбарьерная среда', true, NOW()),
  ('low_sink', 'Низкая раковина', 'Безбарьерная среда', true, NOW()),
  ('tilted_mirror', 'Наклонное зеркало', 'Безбарьерная среда', true, NOW()),
  ('barrier_free_shower', 'Душевая без порогов', 'Безбарьерная среда', true, NOW()),
  ('shower_chair', 'Стул для душа', 'Безбарьерная среда', true, NOW()),
  ('safe', 'Сейф', 'Безопасность', true, NOW()),
  ('lockers', 'Запирающиеся шкафчики', 'Безопасность', true, NOW()),
  ('private_entrance', 'Отдельный вход', 'Дополнительно', true, NOW())
ON CONFLICT ("id") DO UPDATE
SET
  "name" = EXCLUDED."name",
  "category" = EXCLUDED."category",
  "isActive" = true,
  "updatedAt" = NOW();