ALTER TABLE "Excursion" ADD COLUMN IF NOT EXISTS "contactPhoneName" TEXT;
ALTER TABLE "Excursion" ADD COLUMN IF NOT EXISTS "contactPhone2Name" TEXT;
ALTER TABLE "Excursion" ADD COLUMN IF NOT EXISTS "contactPhone3" TEXT;
ALTER TABLE "Excursion" ADD COLUMN IF NOT EXISTS "contactPhone3Name" TEXT;

ALTER TABLE "Transfer" ADD COLUMN IF NOT EXISTS "phoneName" TEXT;
ALTER TABLE "Transfer" ADD COLUMN IF NOT EXISTS "phone2Name" TEXT;
ALTER TABLE "Transfer" ADD COLUMN IF NOT EXISTS "phone3" TEXT;
ALTER TABLE "Transfer" ADD COLUMN IF NOT EXISTS "phone3Name" TEXT;
