ALTER TABLE "Excursion"
ADD COLUMN IF NOT EXISTS "physicalRequirements" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS "whatToBring" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS "meetingPointLat" DECIMAL(9, 6),
ADD COLUMN IF NOT EXISTS "meetingPointLng" DECIMAL(9, 6),
ADD COLUMN IF NOT EXISTS "minBookingNoticeHours" INTEGER,
ADD COLUMN IF NOT EXISTS "hasGuideLicense" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "timeline" JSONB NOT NULL DEFAULT '[]'::JSONB,
ADD COLUMN IF NOT EXISTS "pricingTiers" JSONB NOT NULL DEFAULT '[]'::JSONB,
ADD COLUMN IF NOT EXISTS "faqItems" JSONB NOT NULL DEFAULT '[]'::JSONB,
ADD COLUMN IF NOT EXISTS "includedItems" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS "excludedItems" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS "transferDetails" TEXT,
ADD COLUMN IF NOT EXISTS "cancellationPolicyType" TEXT;
