// Reusable UI helper/component for amenity icon.
import {
  Accessibility,
  AirVent,
  Archive,
  Armchair,
  ArrowUpDown,
  AudioLines,
  Baby,
  Bath,
  BedDouble,
  Blinds,
  BriefcaseBusiness,
  Building2,
  CircleAlert,
  Coffee,
  CookingPot,
  DoorOpen,
  Fan,
  Flame,
  Footprints,
  Glasses,
  GlassWater,
  House,
  LampDesk,
  LockKeyhole,
  Monitor,
  Mountain,
  PanelsTopLeft,
  PawPrint,
  PlugZap,
  Refrigerator,
  Shirt,
  ShowerHead,
  Sparkles,
  Toilet,
  Trees,
  Tv,
  TvMinimalPlay,
  Usb,
  WashingMachine,
  Waves,
  Wifi,
  Wind,
} from "lucide-react";
import { cn } from "@/lib/cn";
import { AppIcon, type LucideIcon } from "@/components/ui/app-icon";

const amenityIconById: Record<string, LucideIcon> = {
  beds_base: BedDouble,
  shower: ShowerHead,
  bath: Bath,
  shower_cabin: ShowerHead,
  toilet: Toilet,
  urinal: Toilet,
  bidet: Bath,
  hygienic_shower: ShowerHead,
  toiletries: Sparkles,
  hair_dryer: Wind,
  bathrobe: Shirt,
  slippers: Footprints,
  air_conditioner: AirVent,
  fan: Fan,
  heating: Flame,
  heater: Flame,
  fireplace: Flame,
  electric_blanket: Flame,
  heated_floor: Flame,
  private_kitchen: CookingPot,
  kitchenette: CookingPot,
  refrigerator: Refrigerator,
  stove: CookingPot,
  oven: CookingPot,
  microwave: CookingPot,
  kettle: Coffee,
  coffee_machine: Coffee,
  cookware: CookingPot,
  mini_bar: GlassWater,
  water_tea_coffee: GlassWater,
  washing_machine: WashingMachine,
  dryer_machine: WashingMachine,
  clothes_dryer: Shirt,
  iron: Shirt,
  ironing_board: Shirt,
  panoramic_windows: PanelsTopLeft,
  no_window: CircleAlert,
  balcony: PanelsTopLeft,
  view_city: Building2,
  city_view: Building2,
  view_river: Waves,
  view_lake: Waves,
  view_sea: Waves,
  sea_view: Waves,
  partial_sea_view: Waves,
  view_ocean: Waves,
  ocean_view: Waves,
  view_embankment: Waves,
  view_forest: Trees,
  forest_view: Trees,
  view_mountain: Mountain,
  mountain_view: Mountain,
  view_stadium: Building2,
  view_landmark: Building2,
  view_courtyard: House,
  wifi: Wifi,
  desk: BriefcaseBusiness,
  sockets_near_desk: PlugZap,
  adapter: PlugZap,
  usb_port: Usb,
  work_chair: Armchair,
  desk_lamp: LampDesk,
  monitor: Monitor,
  tv: Tv,
  online_cinema: TvMinimalPlay,
  yandex_station: AudioLines,
  kids_slippers: Footprints,
  kids_bathrobe: Shirt,
  kids_toiletries: Sparkles,
  playpen: Baby,
  feeding_chair: Baby,
  changing_table: Baby,
  baby_bath: Bath,
  baby_monitor: Baby,
  pet_food_bowl: PawPrint,
  pet_water_bowl: PawPrint,
  pet_toiletries: PawPrint,
  pet_bed: PawPrint,
  pet_towels: PawPrint,
  pet_pads: PawPrint,
  pet_cleanup_bags: PawPrint,
  pet_food: PawPrint,
  pet_friendly: PawPrint,
  pet_bowls: PawPrint,
  paw: PawPrint,
  bedside_handrails: Accessibility,
  bath_handrails: Accessibility,
  toilet_handrails: Accessibility,
  low_sink: Accessibility,
  tilted_mirror: Accessibility,
  barrier_free_shower: Accessibility,
  wheelchair_access: Accessibility,
  elevator: ArrowUpDown,
  ramp: Accessibility,
  accessible_space: Accessibility,
  shower_chair: Accessibility,
  safe: LockKeyhole,
  lockers: Archive,
  private_entrance: DoorOpen,
  blackout_curtains: Blinds,
  curtains: Blinds,
  reading_glasses: Glasses,
};

type AmenityIconProps = {
  featureId?: string | null;
  className?: string;
};

export function AmenityIcon({ featureId, className }: AmenityIconProps) {
  const Icon = featureId ? amenityIconById[featureId] : null;
  return <AppIcon icon={Icon ?? Sparkles} className={cn("h-4 w-4", className)} />;
}

type KeyAmenityIconProps = {
  className?: string;
};

export function KeyAmenityIcon({ className }: KeyAmenityIconProps) {
  return <AppIcon icon={Sparkles} className={cn("h-4 w-4", className)} />;
}
